### ISSUE TITLE
List of use cases

### ISSUE THREAD

**Issue by mirdaki** [ufosc/club-admin-portal#2]
This should be an inclusive list of all the use cases we need to meet. Please feel free to suggest more (and I will create an issue for each respective feature). Most functionality will be about data interaction and visualization. The data itself will be stored in a database you can access via a REST API. Any interaction with GitHub or Google Calendar will be handled by the backend.

- [ ] Officers will be able to sign in to access information
- [ ] Add a new member
- [ ] Let project leads update the project description, URL, and active status
- [ ] Submit an expense to be processed
- [ ] Allow treasurer to approve and reimburse an expense
- [ ] Allow officers to create a new event with time, location, event picture, etc
- [ ] Allow officers to modify any part of an existing event
- [ ] Allow officers to see which members are on which projects, and who isn't on a project
- [ ] Let project leads add members to their project
- [ ] Let officers get data on sign-ins
  - [ ] Visualize a graph of attendance on a meeting to meeting basis
  - [ ] Track number of first time sign-ins per meeting
  - [ ] See what meetings specific members go to
- [ ] Pull generated text about upcoming events for email or Facebook announcements (or actually be able to send out announcements via the List-serve and Facebook)
- [ ] Officer should be able to save weekly announcements anyone can access
- [ ] Add a member to a the club server with a username. A temporary password, that officers can't see, should be sent to that user so they can login
- [ ] Resource text should be kept up-to-date with the club's resources repository (maybe vice-versa)
- [ ] Allow officers to remove members (which would affect them signing into GitHub and the server)
- [ ] Allow Secretary to add meeting notes to events
- [ ] Sign-ins should expire after 15 minutes of unused
- [ ]
